version: '2'

services:
  db:
    build:
      context:  ./
      dockerfile: Dockerfile.postgres
    ports:
      - "65432:5432"
    environment:
      - PGDATA=/var/lib/postgres/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - 'db'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - '.:/onebitexchange'
      - 'gems:/gems'
    stdin_open: true
    tty: true

volumes:
  pgdata:
    driver:  local
  postgres:
  gems:
